baseurl = "http://bhberson.github.io/wilder-beard/"
languageCode = "en-us"
title = "Wilder Beard Company"
googleanalytics = "XX-00000000-0"
copyright = "© 2016 Wilder Beard Company. All Rights Reserved"
disableRSS = true
canonifyurls = true

[params]
  tagline = "Purveyors of Men's Grooming Products"
  subtagline = "Handcrafted by Local Artisans"
  description = "Here in West Michigan, we make all natural, quality products. Every beard and moustache is unique. We offer balms and waxes handmade with every sort in mind. From heavy waxes and balms to tame the wildest moustaches and manes, to light and conditioning balms for a softer gentler hold."
  # twitter = "wilderbeardco"
  facebook = "wilderbeardco"
  fbpageID = "1447423692187963"
  instagram = "wilderbeardco"
  phone = "(231) 123-1234"
  address1 = ""
  address2 = "North Muskegon, MI 49445"
  googlemaps = "https://goo.gl/maps/"
  email = "info@pigeonhillbrew.com"
  disclaimer = "Disclaimer: Our products are intended for external use only. If irritation should occur, please discontinue use. The statements presented on this site have not been evaluated by the Food and Drug Administration. The products offered by Wilder Beard Company are not intended to diagnose, treat, cure or prevent any disease."
